// import Head from 'next/head'
// import Image from 'next/image'
// // import Footer from '../components/Footer'
// // import Header from '../components/Header'
// import styles from '../styles/Home.module.css'
// import styles from '../styles/Service.module.css'

export default function Contact() {
    return (
        <div className="">
            {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
            <section className="">
                <div className="container px-4 py-14 md:py-24 mx-auto">
                    <div className="max-w-3xl my-10 w-full">
                        <h2 className="text-7xl text-primary font-title font-normal tracking-[2.5px]">
                            HIRE US
                        </h2>
                        <p className="text-2xl text-dark tracking-[1.5px] leading-loose">
                            Got a question? Have an idea that you want to develop? Want to quadruple your sales in no time?
                            Send us an email at &nbsp; 
                            <a href="mailto:interior@p&a.com" className="font-bold">interior@p&a.com</a>, &nbsp;
                            give us a call at &nbsp; 
                            <a href="tel:+971 58 267 4671" className="">+971 58 267 4671</a>.
                        </p>
                    </div>
                    <div className="max-w-3xl my-10 w-full">
                        <h2 className="text-7xl text-primary font-title font-normal tracking-[2.5px]">
                            GET HIRED
                        </h2>
                        <p className="text-2xl text-dark tracking-[1.5px] leading-loose">
                            Bored? Think you’re a hot match? Are your skills going to waste?
                            Send us your CV and say hello on &nbsp; 
                            <a href="mailto:joinus@p&a.com" className="font-bold"> joinus@p&a.com </a> &nbsp;
                            or fill in &nbsp; 
                            <a href="http://" className="border-b-4 border-primary">THIS FORM</a> &nbsp;
                            and we will check you out.
                            To see all the positions that are currently open please click 
                            <a href="" className="font-bold"> HERE</a>.
                        </p>
                    </div>
                </div>
            </section>

        </div>
    )
}
