import Head from 'next/head';
import AboutSection from '../components/home/AboutSection';
import FaqSection from '../components/home/FaqSection';
import HeroSection from '../components/home/HeroSection';
import PortfolioSection from '../components/home/PortfolioSection';
import ProcesSection from '../components/home/ProcessSection';
import ReviewsSection from '../components/home/ReviewsSection';
import Testimonial from '../components/home/Testimonial';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <AboutSection />
      <ProcesSection />
      <ReviewsSection />
      <PortfolioSection />
      <Testimonial />
      <FaqSection />
    </div>
  )
}
